/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IEntityFactory } from "./IEntityFactory";
export type { IGame } from "./IGame";
export type { PlayMintContext } from "./PlayMintContext";
