/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IEntity } from "./IEntity";
export type { IGameFuncEntity } from "./IGameFuncEntity";
export type { INumberEntity } from "./INumberEntity";
