/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export type ComponentSummaryStruct = {
  component: AddressLike;
  functions: string[];
  abis: string[];
  required: string[];
  displayName: string;
  description: string;
};

export type ComponentSummaryStructOutput = [
  component: string,
  functions: string[],
  abis: string[],
  required: string[],
  displayName: string,
  description: string
] & {
  component: string;
  functions: string[];
  abis: string[];
  required: string[];
  displayName: string;
  description: string;
};

export interface QueueSessionInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "abis"
      | "functions"
      | "getPlayerCount"
      | "getSummary"
      | "initialize"
      | "joinGame"
      | "required"
      | "setMatchOrWait"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "JoinedQueue" | "MatchMade"): EventFragment;

  encodeFunctionData(functionFragment: "abis", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "functions",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPlayerCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getSummary",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "joinGame",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "required",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMatchOrWait",
    values: [AddressLike, AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "abis", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "functions", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getPlayerCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getSummary", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "joinGame", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "required", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setMatchOrWait",
    data: BytesLike
  ): Result;
}

export namespace JoinedQueueEvent {
  export type InputTuple = [player: AddressLike, queueSize: BigNumberish];
  export type OutputTuple = [player: string, queueSize: bigint];
  export interface OutputObject {
    player: string;
    queueSize: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MatchMadeEvent {
  export type InputTuple = [player1: AddressLike, player2: AddressLike];
  export type OutputTuple = [player1: string, player2: string];
  export interface OutputObject {
    player1: string;
    player2: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface QueueSession extends BaseContract {
  connect(runner?: ContractRunner | null): QueueSession;
  waitForDeployment(): Promise<this>;

  interface: QueueSessionInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  abis: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  functions: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  getPlayerCount: TypedContractMethod<[game: AddressLike], [bigint], "view">;

  getSummary: TypedContractMethod<[], [ComponentSummaryStructOutput], "view">;

  initialize: TypedContractMethod<[game: AddressLike], [void], "nonpayable">;

  joinGame: TypedContractMethod<
    [executor: AddressLike, gameAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  required: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  setMatchOrWait: TypedContractMethod<
    [executor: AddressLike, gameAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "abis"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "functions"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getPlayerCount"
  ): TypedContractMethod<[game: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getSummary"
  ): TypedContractMethod<[], [ComponentSummaryStructOutput], "view">;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<[game: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "joinGame"
  ): TypedContractMethod<
    [executor: AddressLike, gameAddress: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "required"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "setMatchOrWait"
  ): TypedContractMethod<
    [executor: AddressLike, gameAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "JoinedQueue"
  ): TypedContractEvent<
    JoinedQueueEvent.InputTuple,
    JoinedQueueEvent.OutputTuple,
    JoinedQueueEvent.OutputObject
  >;
  getEvent(
    key: "MatchMade"
  ): TypedContractEvent<
    MatchMadeEvent.InputTuple,
    MatchMadeEvent.OutputTuple,
    MatchMadeEvent.OutputObject
  >;

  filters: {
    "JoinedQueue(address,uint256)": TypedContractEvent<
      JoinedQueueEvent.InputTuple,
      JoinedQueueEvent.OutputTuple,
      JoinedQueueEvent.OutputObject
    >;
    JoinedQueue: TypedContractEvent<
      JoinedQueueEvent.InputTuple,
      JoinedQueueEvent.OutputTuple,
      JoinedQueueEvent.OutputObject
    >;

    "MatchMade(address,address)": TypedContractEvent<
      MatchMadeEvent.InputTuple,
      MatchMadeEvent.OutputTuple,
      MatchMadeEvent.OutputObject
    >;
    MatchMade: TypedContractEvent<
      MatchMadeEvent.InputTuple,
      MatchMadeEvent.OutputTuple,
      MatchMadeEvent.OutputObject
    >;
  };
}
