/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export type ComponentSummaryStruct = {
  component: AddressLike;
  functions: string[];
  abis: string[];
  required: string[];
  displayName: string;
  description: string;
};

export type ComponentSummaryStructOutput = [
  component: string,
  functions: string[],
  abis: string[],
  required: string[],
  displayName: string,
  description: string
] & {
  component: string;
  functions: string[];
  abis: string[];
  required: string[];
  displayName: string;
  description: string;
};

export declare namespace RockPaperScissors {
  export type HandStruct = { player: AddressLike; actionIndex: BigNumberish };

  export type HandStructOutput = [player: string, actionIndex: bigint] & {
    player: string;
    actionIndex: bigint;
  };
}

export interface RockPaperScissorsInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "abis"
      | "functions"
      | "getSummary"
      | "initialize"
      | "oneOnOne"
      | "required"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "GameResult"): EventFragment;

  encodeFunctionData(functionFragment: "abis", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "functions",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getSummary",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "oneOnOne",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "required",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "abis", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "functions", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getSummary", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "oneOnOne", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "required", data: BytesLike): Result;
}

export namespace GameResultEvent {
  export type InputTuple = [
    player1: RockPaperScissors.HandStruct,
    player2: RockPaperScissors.HandStruct,
    winner: AddressLike
  ];
  export type OutputTuple = [
    player1: RockPaperScissors.HandStructOutput,
    player2: RockPaperScissors.HandStructOutput,
    winner: string
  ];
  export interface OutputObject {
    player1: RockPaperScissors.HandStructOutput;
    player2: RockPaperScissors.HandStructOutput;
    winner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface RockPaperScissors extends BaseContract {
  connect(runner?: ContractRunner | null): RockPaperScissors;
  waitForDeployment(): Promise<this>;

  interface: RockPaperScissorsInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  abis: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  functions: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  getSummary: TypedContractMethod<[], [ComponentSummaryStructOutput], "view">;

  initialize: TypedContractMethod<[game: AddressLike], [void], "nonpayable">;

  oneOnOne: TypedContractMethod<
    [executor: AddressLike, gameAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  required: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "abis"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "functions"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getSummary"
  ): TypedContractMethod<[], [ComponentSummaryStructOutput], "view">;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<[game: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "oneOnOne"
  ): TypedContractMethod<
    [executor: AddressLike, gameAddress: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "required"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  getEvent(
    key: "GameResult"
  ): TypedContractEvent<
    GameResultEvent.InputTuple,
    GameResultEvent.OutputTuple,
    GameResultEvent.OutputObject
  >;

  filters: {
    "GameResult(tuple,tuple,address)": TypedContractEvent<
      GameResultEvent.InputTuple,
      GameResultEvent.OutputTuple,
      GameResultEvent.OutputObject
    >;
    GameResult: TypedContractEvent<
      GameResultEvent.InputTuple,
      GameResultEvent.OutputTuple,
      GameResultEvent.OutputObject
    >;
  };
}
