/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Reward20Entity } from "./Reward20Entity";
export type { SimpleMintableERC20 } from "./SimpleMintableERC20";
