/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Reward20Entity__factory } from "./Reward20Entity__factory";
export { SimpleMintableERC20__factory } from "./SimpleMintableERC20__factory";
