/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  SimpleMintableERC20,
  SimpleMintableERC20Interface,
} from "../../../../src/entities/Reward20Entity.sol/SimpleMintableERC20";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "mint",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class SimpleMintableERC20__factory {
  static readonly abi = _abi;
  static createInterface(): SimpleMintableERC20Interface {
    return new Interface(_abi) as SimpleMintableERC20Interface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): SimpleMintableERC20 {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as SimpleMintableERC20;
  }
}
