/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DailyInteractionEntity } from "./DailyInteractionEntity";
export type { IERC721 } from "./IERC721";
