/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IEntity__factory } from "./IEntity__factory";
export { IGameFuncEntity__factory } from "./IGameFuncEntity__factory";
export { INumberEntity__factory } from "./INumberEntity__factory";
