import { defineConfig } from '@wagmi/cli';
import { foundry } from '@wagmi/cli/plugins'
import { react } from '@wagmi/cli/plugins'

export default defineConfig({
  out: 'src/generated.ts',
  contracts: [],
  plugins: [
    foundry({
      project: '../chain',
      include: [
        'ComponentRegistry.sol/**',
        'D7.sol/**',
        'Game.sol/**',
        'GameFactory.sol/**',
        'IGame.sol/**',
        'IComponent.sol/**',
      ],
      // exclude: [ 
      //   'AccessControl.sol/**',
      //   'Base.sol/**',
      //   'Catch.t.sol/**',
      //   'CatchEntity.sol/**',
      //   // 'ComponentRegistry.sol/**',
      //   'Context.sol/**',
      //   // 'D7.sol/**',
      //   'DailyInteractionEntity.sol/**',
      //   // 'DailyInteractionModule.sol/**',
      //   'DeployCatch.s.sol/**',
      //   'DeployDice.s.sol/**',
      //   'DeployProtocol.s.sol/**',
      //   'ERC165.sol/**',
      //   'ERC721/**',
      //   'ERC721.sol/**',
      //   'ERC721A.sol/**',
      //   'EntityFactory.sol/**',
      //   // 'Game.sol/**',
      //   // 'GameFactory.sol/**',
      //   'IAccessControl.sol/**',
      //   'IComponent.sol/**',
      //   'IERC165.sol/**',
      //   'IERC20.sol/**',
      //   'IERC721.sol/**',
      //   'IERC721A.sol/**',
      //   'IERC721Metadata.sol/**',
      //   'IERC721Receiver.sol/**',
      //   'IEntity.sol/**',
      //   'IEntityFactory.sol/**',
      //   'IGame.sol/**',
      //   'IMulticall3.sol/**',
      //   'Initializable.sol/**',
      //   'LibClone.sol/**',
      //   'MMONeighborInteractionEntity.sol/**',
      //   // 'MMONeighborInteractionModule.sol/**',
      //   'MMOSessionEntity.sol/**',
      //   // 'MMOSessionModule.sol/**',
      //   'Math.sol/**',
      //   'MockERC20.sol/**',
      //   'MockERC721.sol/**',
      //   'MockNFT.sol/**',
      //   'OneOff.s.sol/**',
      //   'PlayMintContext.sol/**',
      //   'Script.sol/**',
      //   'SignedMath.sol/**',
      //   'StdAssertions.sol/**',
      //   'StdChains.sol/**',
      //   'StdCheats.sol/**',
      //   'StdError.sol/**',
      //   'StdInvariant.sol/**',
      //   'StdJson.sol/**',
      //   'StdMath.sol/**',
      //   'StdStorage.sol/**',
      //   'StdStyle.sol/**',
      //   'StdToml.sol/**',
      //   'StdUtils.sol/**',
      //   'Strings.sol/**',
      //   'Test.sol/**',
      //   'Vm.sol/**',
      //   'console.sol/**',
      //   'console2.sol/**',
      //   'draft-IERC6093.sol/**',
      //   'introspection/**',
      //   'safeconsole.sol/**'
      // ], 
    }),
    react()
  ],
});
